basicmooc/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from simplemooc.accounts.views import register, edit, dashboard, edit_password, password_reset, password_reset_confirm

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    url(r'^entrar/$', auth_views.login, {'template_name':'accounts/login.html'}, name='login'),
    url(r'^sair/$', auth_views.logout, {'next_page':'core:home'}, name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^nova-senha/$', password_reset, name='password_reset'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^editar/$', edit, name='edit'),
    url(r'^editar-senha/$', edit_password, name='edit_password'),
]

basicmooc/core/urls.py
from django.conf.urls import url

from simplemooc.core.views import home, contact

urlpatterns = [
    url('^$', home, name='home'),
    url('^contato/$', contact, name='contact')
]

basicmooc/courses-example/urls.py
from django.conf.urls import url

from simplemooc.courses.views import index, details, enrollment, \
    announcements, undo_enrollment, show_announcement, lessons, lesson, material

urlpatterns = [
    url('^$', index, name='index'),
    url('^(?P<slug>[\w_-]+)/$', details, name='details'),
    url('^(?P<slug>[\w_-]+)/inscricao/$', enrollment, name='enrollment'),
    url('^(?P<slug>[\w_-]+)/anuncios/$', announcements, name='announcements'),
    url('^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$', show_announcement, name='show_announcement'),
    url('^(?P<slug>[\w_-]+)/cancelar-inscricao/$', undo_enrollment, name='undo_enrollment'),
    url('^(?P<slug>[\w_-]+)/aulas/$', lessons, name='lessons'),
    url('^(?P<slug>[\w_-]+)/aula/(?P<pk>\d+)/$', lesson, name='lesson'),
    url('^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$', material, name='material'),
]

basicmooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basicmooc/core/models.py
from django.db import models

basicmooc/core/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse

def home(request):
    #return HttpResponse('hello world')
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

basicmooc/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'courses:index' %}">Cursos</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:dashboard' %}">Painel</a></li>
            <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">

    {% if messages %}
    <div class="pure-g-r content-ribbon">
        <aside class="pure-u-1">
            {% for message in messages %}
            <p>{{ message}}</p>
            {% endfor %}
        </aside>
    </div>
    {% endif %}

    {% block content %}{% endblock %}
    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>

basicmooc/core/templates/contact.html
{% extends "base.html" %}

{% block content %}

<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h1>Fale Conosco</h1>
        <p>Você pode entrar em contato conosco pelas formas listadas abaixo:</p>
        <h4>Links:</h4>
        <ul>
            <li>Email: <a href="#">contato@basicmooc.com.br</a></li>
            <li>Twitter: <a href="#">@basicmooc</a></li>
        </ul>
    </div>
</div>

{% endblock %}

basicmooc/core/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    Uma Plataforma de Ensino a Distância com cursos gratuitos
                </h1>
                <h2 class="splash-subhead">
                    A Basic MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Saiba mais</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
            <h3>Publique suas aulas</h3>
            <p>
                A Basic MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Vídeo aulas e materiais digitais.">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Fórum de Dúvidas">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Fórum de Dúvidas</h4>
            <h3>Interaja com seus Alunos</h3>
            <p>
                Na Basic MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Exercícios</h4>
            <h3>Crie exercícios para avaliar seus alunos</h3>
            <p>
                Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Exercícios">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Mural de Avisos">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Mural de Avisos</h4>
            <h3>Envie anúncios diretamente para os alunos</h3>
            <p>
                Organize os avisos do seu curso de forma fácil e simples.
            </p>
        </div>
    </div>
</div>
{% endblock %}