basicmooc/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from simplemooc.accounts.views import register, edit, dashboard, edit_password, password_reset, password_reset_confirm

urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    url(r'^entrar/$', auth_views.login, {'template_name':'accounts/login.html'}, name='login'),
    url(r'^sair/$', auth_views.logout, {'next_page':'core:home'}, name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^nova-senha/$', password_reset, name='password_reset'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^editar/$', edit, name='edit'),
    url(r'^editar-senha/$', edit_password, name='edit_password'),
]

basicmooc/courses-example/urls.py
from django.conf.urls import url

from simplemooc.courses.views import index, details, enrollment, \
    announcements, undo_enrollment, show_announcement, lessons, lesson, material

urlpatterns = [
    url('^$', index, name='index'),
    url('^(?P<slug>[\w_-]+)/$', details, name='details'),
    url('^(?P<slug>[\w_-]+)/inscricao/$', enrollment, name='enrollment'),
    url('^(?P<slug>[\w_-]+)/anuncios/$', announcements, name='announcements'),
    url('^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$', show_announcement, name='show_announcement'),
    url('^(?P<slug>[\w_-]+)/cancelar-inscricao/$', undo_enrollment, name='undo_enrollment'),
    url('^(?P<slug>[\w_-]+)/aulas/$', lessons, name='lessons'),
    url('^(?P<slug>[\w_-]+)/aula/(?P<pk>\d+)/$', lesson, name='lesson'),
    url('^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$', material, name='material'),
]

basicmooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basicmooc/accounts/models.py
import re

from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin, UserManager)
from django.db import models
from django.core import validators
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Nome de Usuário', max_length=30, unique=True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
                                              'O nome de usuário só pode conter letras e digitos.',
                                              'invalid'
                                              )])
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class PasswordReset(models.Model):

    user  = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Usuário',
        related_name='resets'
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado', default=False, blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova senha'
        verbose_name_plural = 'Novas senhas'
        ordering = ['-created_at']

basicmooc/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import PasswordReset

from simplemooc.core.mail import send_email_template
from simplemooc.core.utils import generate_hash_key

User = get_user_model()

class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError('Nenhum usuário encontrado com esse e-mail.')

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Criar nova senha no Simple MOOC'
        context = {
            'reset' : reset
        }
        send_email_template(subject, template_name, context, ['user.email'])

class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação de Senha', widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                'A confirmação de senha não está correta!',
                code='password_mistach'
            )
        return password2


    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']

class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name']

basicmooc/accounts/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib import messages

from simplemooc.courses.models import Enrollment

from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset

User = get_user_model()

@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    context = {}
    context['enrollments'] = Enrollment.objects.filter(user=request.user)
    return render(request, template_name, context)

def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(username=user.username, password=form.cleaned_data['password1'])
            login(request, user)
            return redirect('core:home')
    else:
        form = RegisterForm()
    context = {
        'form':form
    }
    return render(request, template_name, context)

def password_reset(request):
    context = {}
    template_name = 'accounts/password_reset.html'
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

def password_reset_confirm(request, key):
    context = {}
    template_name = 'accounts/password_reset_confirm.html'
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Os dados foram alterados com sucesso.')
            return redirect('accounts:dashboard')
    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request, template_name, context)

@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

basicmooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load courses_tags %}

{% block content %}
<div class="pure-g-r content-ribbon">

    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <a href="{% url 'accounts:dashboard' %}">Meu Painel</a>
            {% endblock %}
        </ul>
    </div>

    <div class="pure-u-1">
        <p>Bem-vindo, {{user}}</p>
    </div>

    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <a class="pure-menu-heading">Meus Cursos</a>
            <ul>
                {% block menu_options %}
                    {% my_courses user %}
                    <li class="pure-menu-heading">Minha Conta</li>
                    <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
                    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
                {% endblock %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <h2>Meus Cursos</h2>
            {% for enrollment in enrollments %}
            <div class="well">
                <h3>{{enrollment.course}}</h3>
                <h2>{{enrollment.course.start_date|date:'d/m/Y'|default:'Sem data'}}</h2>
                {{ enrollment.course.description|linebreaks }}
                <div class="pure-controls">
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}" class="pure-button pure-button-primary">Acessar</a>
                    <a href="{% url 'courses:undo_enrollment' enrollment.course.slug    %}" class="pure-button pure-button-error">Cancelar</a>
                </div>
            </div>
            {% empty %}
            <aside class="pure-u-1"><p>Nenhum curso inscrito.</p></aside>
            {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

basicmooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% load static %}

{% block breadcrumb %}
{{ block.super }}
/ <a href="#">Editar Conta</a>
{% endblock %}

{% block dashboard_content %}

<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Enviar</button>
        </div>
    </fieldset>
</form>

{% endblock%}

basicmooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

basicmooc/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="{% url 'accounts:password_reset' %}" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}

basicmooc/accounts/templates/accounts/password_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Sua senha foi criada com sucesso</p>
        {% else %}
        <h2>Informe sua nova Senha</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

basicmooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Um e-mail foi enviando para você com mais detalhes de como criar uma nova senha</p>
        {% else %}
        <h2>Informe seu E-mail</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

basicmooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Sua senha foi criada com sucesso</p>
        {% else %}
        <h2>Informe sua nova Senha</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

basicmooc/accounts/templates/accounts/password_reset_mail.html
<p>Para criar uma nova senha, acesse o link:
    <a href="http://127.0.0.1:8000{% url 'accounts:password_reset_confirm' reset.key %}" title="Link para Criar Nova Senha">
    Criar Nova Senha
</a>
</p>

basicmooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}